# Write your MySQL query statement below
SELECT WEATHER1.ID FROM 
WEATHER WEATHER1 , WEATHER WEATHER2
WHERE
DATEDIFF(WEATHER1.RECORDDATE, WEATHER2.RECORDDATE) = 1
AND WEATHER1.TEMPERATURE > WEATHER2.TEMPERATURE;